### ISSUE TITLE
RSSAid not appearing when trying to share

### ISSUE THREAD

**Issue by oliroe** [LeetaoGoooo/RSSAid#50]
In version 1.6.5 if I was on GitHub on Chrome I could click share and share the webpage with RSSAid which would show the available RSS feeds. Version 2.0.1 does not appear

I have uninstalled 2.0.1 and installed 1.6.5 and it becomes selectable again so there's definitely an issue with the latest version

**Comment by oliroe** [comment]
![Screenshot_20240610-204210.png](https://github.com/LeetaoGoooo/RSSAid/assets/4500141/201da53b-5acb-4b3f-8229-06fefd26e609)

Could it be the removal of the SEND intent?

**Comment by LeetaoGoooo** [comment]
thank you for feedback,I’ll fix it in the next few days 😂

**Comment by LeetaoGoooo** [comment]
> ![Screenshot_20240610-204210.png](https://private-user-images.githubusercontent.com/4500141/338321225-201da53b-5acb-4b3f-8229-06fefd26e609.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMTMwNDgsIm5iZiI6MTcyMTIxMjc0OCwicGF0aCI6Ii80NTAwMTQxLzMzODMyMTIyNS0yMDFkYTUzYi01YWNiLTRiM2YtODIyOS0wNmZlZmQyNmU2MDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMTAzOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTIxMDI0NTQ2MTE0ODEwNGNjYzg1N2FkM2YxYWJiNGZhY2U4YzRjYWY4YWRmMzczYjMwYWZhMGY5MjVmNGY5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e6JRw1Y2hDwHAkjur7ySJb4JBOsoUjE-fW9o87NNmxI)
> 
> Could it be the removal of the SEND intent?

Sorry for the delay in fixing this. I've recovered the code. Please let me know if it works

**Comment by oliroe** [comment]
![Screenshot_20240717-115859](https://github.com/user-attachments/assets/eb9de13f-8e32-4f8d-9974-c0e44fa3146d)
![Screenshot_20240717-115836](https://github.com/user-attachments/assets/cb9e7b67-4649-477a-8366-6d9c7ff3562d)

**Comment by LeetaoGoooo** [comment]
> ![Screenshot_20240717-115836](https://private-user-images.githubusercontent.com/4500141/349476342-cb9e7b67-4649-477a-8366-6d9c7ff3562d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMTUxNjIsIm5iZiI6MTcyMTIxNDg2MiwicGF0aCI6Ii80NTAwMTQxLzM0OTQ3NjM0Mi1jYjllN2I2Ny00NjQ5LTQ3N2EtODM2Ni02ZDljN2ZmMzU2MmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTdUMTExNDIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZmMzMzVlM2E0ODUyMWExOTg2MzI1NTRjNjg1MGY5ZmFkYjQ5YTg4NzM4YWQ3NzE1ZjA5NDExYTQyZmIxMzk3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1VCuxNfeow2VXiVlRmlkCP1Cp_BPvr_ssLBvtK_sKqM)

thanks man~~

**Comment by oliroe** [comment]
Sorry, was part way through editing my reply. It's partially fixed in that it now appears in the share menu but it doesn't bring the details of the link through

**Comment by LeetaoGoooo** [comment]
> Sorry, was part way through editing my reply. It's partially fixed in that it now appears in the share menu but it doesn't bring the details of the link through

Yeah, you're right. Let me reopen this issue and then  look into this problem.

**Comment by LeetaoGoooo** [comment]
> Sorry, was part way through editing my reply. It's partially fixed in that it now appears in the share menu but it doesn't bring the details of the link through

new version is released and now you can see link preview in app

**Comment by oliroe** [comment]
Just letting you know this hasn't resolved it for me. I've cleared cache and removed all versions of the app and started again with 2.0.2. If i share a link to the app the preview isn't shown as it did with 1.6.5

**Comment by LeetaoGoooo** [comment]
> Just letting you know this hasn't resolved it for me. I've cleared cache and removed all versions of the app and started again with 2.0.2. If i share a link to the app the preview isn't shown as it did with 1.6.5

It's wired ~ it works on my phone,let me double check tomorrow

**Comment by LeetaoGoooo** [comment]
> Just letting you know this hasn't resolved it for me. I've cleared cache and removed all versions of the app and started again with 2.0.2. If i share a link to the app the preview isn't shown as it did with 1.6.5

yeah,you're right. I just replaced the previous preview link component with a new one,so it looks like a little different from before. And then I will add new theme for rssaid

**Comment by oliroe** [comment]
Given this issue is now closed would you like me to open another one?

**Comment by LeetaoGoooo** [comment]
> Given this issue is now closed would you like me to open another one?

I just reopen this issue. Have you tried the latest version 3.0.0 ?  There are a ui for the RSSAid and also for the preview link.

![Simulator Screenshot - iPhone 15 - 2024-07-23 at 06 49 19](https://github.com/user-attachments/assets/0e736af2-ee3d-42dc-8f68-a093cb11c13c)

**Comment by oliroe** [comment]
![Screenshot_20240723-095523.png](https://github.com/user-attachments/assets/b5c1f1ca-3baf-4e9b-a528-c06152be32af)

Hi

Whenever I share a link on stock Android 14 I see the above, it doesn't include the link address and just opens the app. This is using 3.0.0

**Comment by LeetaoGoooo** [comment]
> ![Screenshot_20240723-095523.png](https://private-user-images.githubusercontent.com/4500141/351257058-b5c1f1ca-3baf-4e9b-a528-c06152be32af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MjY4OTAsIm5iZiI6MTcyMTcyNjU5MCwicGF0aCI6Ii80NTAwMTQxLzM1MTI1NzA1OC1iNWMxZjFjYS0zYmFmLTRlOWItYTUyOC1jMDYxNTJiZTMyYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjNUMDkyMzEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTE0YWQyOWM4MjA2NTI3ZTVhMWM0MjRhZTgxYTgzZTVhYWQxZjA5MjNiMjI0NTFhN2U3ZGExM2IzNTkzNTQ4NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ufN5fuMG8fKWUHaFbdK8ighepgwVIxt0-HlHjq1jZOs)
> 
> Hi
> 
> Whenever I share a link on stock Android 14 I see the above, it doesn't include the link address and just opens the app. This is using 3.0.0

can you see the rules in the config page?

**Comment by LeetaoGoooo** [comment]
Have checked the rules in config page? Is there any content?

**Comment by oliroe** [comment]
![Screenshot_20240723-140321.png](https://github.com/user-attachments/assets/abaf0a6b-e48e-4709-a961-2881f84b0461)

![Screenshot_20240723-140309.png](https://github.com/user-attachments/assets/847ff4f6-a3eb-4139-9e81-4f687669b1b3)

Interestingly if I copy the link from my clipboard it doesn't work either. The rules seem to be populated ok

**Comment by LeetaoGoooo** [comment]
also make a new release to fix this [v3.0.1](https://github.com/LeetaoGoooo/RSSAid/releases/tag/v3.0.1)

**Comment by oliroe** [comment]
Feel free to tell me to go away and stop bothering you 😀

I've cleared the memory and cache of the app, uninstalled it and installed the new release. Now the rules are blank and do not refresh (stays blank). Using the URL of my local instance which is accessible in the browser

**Comment by LeetaoGoooo** [comment]
Make sure your instance is the latest version of rsshub,right now all rules
are updated by api

https://github.com/LeetaoGoooo/RSSAid/issues/47

And if you use access key if may have another issue

https://github.com/LeetaoGoooo/RSSAid/issues/58

**Comment by oliroe** [comment]
My instance of rsshub is updated daily and I don't use an access key. I can't get any version since 1.6.5 to bring back the rules.

Looks like I'm the only one with the problem though

**Comment by LeetaoGoooo** [comment]
> My instance of rsshub is updated daily and I don't use an access key. I can't get any version since 1.6.5 to bring back the rules.
> 
> Looks like I'm the only one with the problem though

emmm could you try to set domain to `https://rsshub.app`  in the config  and then refresh the rules  using v3.0.1 version, which i released last night~ Meanwhile try to  access `your domain/api/radar/rules` to see if the rules are returned in this end-point. check with https://docs.rsshub.app/guide/api

**Comment by oliroe** [comment]
Using the default URL doesn't bring back the rules. 

Mydomain/api/radar/rules in chrome brings back all the rules

**Comment by LeetaoGoooo** [comment]
I know why now. I made a very silly mistake, and I'm currently building the new version. I removed the internet permission from Android.

**Comment by LeetaoGoooo** [comment]
https://github.com/LeetaoGoooo/RSSAid/releases/tag/v3.0.1%2B10 try to use this version

**Comment by oliroe** [comment]
Ok, rules are now pulled back which is great.
Pasting a link now brings back the feed options

Sharing a link with the app still doesn't pull through the link into the app though

**Comment by LeetaoGoooo** [comment]
> Ok, rules are now pulled back which is great.
> Pasting a link now brings back the feed options
> 
> Sharing a link with the app still doesn't pull through the link into the app though

Haha, regardless, I have partially fixed this issue. As for the other problem, I’ll look into it carefully today and fix it as soon as possible.

Also，I'm really appreciate your patience

**Comment by LeetaoGoooo** [comment]
https://github.com/user-attachments/assets/e4d5d875-8e5d-4dbb-b0b3-3bbe12bd90da

for the v3.0.1+11, i think share event is also fixed~~

**Comment by oliroe** [comment]
Done a quick test and all seems to be working now 😀

Appreciate the perseverance

**Comment by LeetaoGoooo** [comment]
> Done a quick test and all seems to be working now 😀
> 
> Appreciate the perseverance

niceeee~~ i'll close this issue.
